[package]
name = "rco-pq"
description = "RCO Protocol — Post-Quantum Dilithium Ledger Bridge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rco-types = { workspace = true }
rco-crypto = { workspace = true }
sha3 = { workspace = true }
pqcrypto-dilithium = "0.4"
pqcrypto-traits = "0.3"
rand = "0.8"
group = "0.13"

[dev-dependencies]
tempfile = "3.15"
rco-quorum = { workspace = true }
